[build]
  publish = ".next"
  command = "pnpm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js 정적 파일 서빙
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Netlify Functions 개별 매핑
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/auth-signup"
  status = 200

[[redirects]]
  from = "/api/auth/forgot-password"
  to = "/.netlify/functions/auth-forgot-password"
  status = 200

[[redirects]]
  from = "/api/auth/resend-confirmation"
  to = "/.netlify/functions/auth-resend-confirmation"
  status = 200

[[redirects]]
  from = "/api/announcements"
  to = "/.netlify/functions/announcements"
  status = 200

[[redirects]]
  from = "/api/announcements/*"
  to = "/.netlify/functions/announcements/:splat"
  status = 200

[[redirects]]
  from = "/api/assignments"
  to = "/.netlify/functions/assignments"
  status = 200

[[redirects]]
  from = "/api/assignments/*"
  to = "/.netlify/functions/assignments/:splat"
  status = 200

[[redirects]]
  from = "/api/attendance"
  to = "/.netlify/functions/attendance"
  status = 200

[[redirects]]
  from = "/api/attendance/*"
  to = "/.netlify/functions/attendance/:splat"
  status = 200

[[redirects]]
  from = "/api/community/*"
  to = "/.netlify/functions/community/:splat"
  status = 200

[[redirects]]
  from = "/api/courses"
  to = "/.netlify/functions/courses"
  status = 200

[[redirects]]
  from = "/api/courses/*"
  to = "/.netlify/functions/courses/:splat"
  status = 200

[[redirects]]
  from = "/api/analytics/*"
  to = "/.netlify/functions/analytics/:splat"
  status = 200

[[redirects]]
  from = "/api/payments/*"
  to = "/.netlify/functions/payments/:splat"
  status = 200

# 나머지 API Routes는 Next.js로 처리 (fallback)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA 라우팅 지원 (가장 마지막에 위치)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Identity 서비스 활성화
[dev]
  functions = "netlify/functions"
  publish = ".next"

# Netlify Functions 설정
[functions]
  node_bundler = "esbuild"

# Build 플러그인
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 환경 변수 (로컬 개발용)
[context.development.environment]
  NEXT_PUBLIC_NETLIFY_SITE_URL = "http://localhost:8888"

# 프로덕션 환경
[context.production.environment]
  NEXT_PUBLIC_NETLIFY_SITE_URL = "$URL"

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://identity.netlify.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com https://*.supabase.co; frame-src https://identity.netlify.com;" 